"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# 1. ENTORNO E ROTAS BASE
# --------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# 2. SEGURANÇA PERIMETRAL (RESOLUÇÃO DE BLOQUEIOS)
# --------------------------------------------------------------------------
# ATENÇÃO: DEBUG deve estar em True no teu laboratório para aceitar renderização local
SECRET_KEY = 'django-insecure-local-dev-key-pure-clean-code-fsf'

DEBUG = True

# Definição estrita de permissões de Host para mitigar o CommandError
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# 3. COMPONENTES E APLICAÇÕES ATIVAS
# --------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # A tua aplicação do Currículo conectada ao ecossistema
    'cv',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'


# 4. MOTOR DE RENDERIZAÇÃO DE TEMPLATES (DJANGO RUNTIME)
# --------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Django vai procurar automaticamente na pasta cv/templates/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# 5. INFRAESTRUTURA DE DADOS RELACIONAIS
# --------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# 6. VALIDADORES DE CREDENCIAIS / SEGURANÇA
# --------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 7. INTERNACIONAÇÃO E LOCALIZAÇÃO
# --------------------------------------------------------------------------
LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# 8. GESTÃO DE ARQUIVOS ESTÁTICOS (CSS, JS, IMAGENS) [CRÍTICO]
# --------------------------------------------------------------------------
STATIC_URL = 'static/'

# Tipo de campo chave primária padrão
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'